apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: anjoysutrisna/test-argo-2048:1.0.0
  name: testargo-2048
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      images:
        - anjoysutrisna/test-argo-2048:1.0.0
    path: 2048/CLUSTER_1
    repoURL: https://github.com/sutrisnaanjoy19/argoCD.git
    targetRevision: HEAD
