apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/cm-java-300806/cm/cm-java/apps/test 
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    path: 2048/
    repoURL: http://tree.mn/sutrishna.a1/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true