apiVersion: v1
kind: Service
metadata:
  name: testargo-2048
  namespace: test
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: testargo-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testargo-2048
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testargo-2048
  template:
    metadata:
      labels:
        app: testargo-2048
    spec:
      imagePullSecrets:
        - name: ar-json-key
      containers:
        - name: backend
          image: anjoysutrisna/test-argo-2048:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testargo-2048-ingress
  annotations:
    kubernetes.io/ingress.class: "misc-nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  namespace: test
spec:
  rules:
    - host: testargo-2048.test.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testargo-2048
                port:
                  number: 80
